#!/usr/bin/env bash
# Generate data/api-reference.txt by running :browse against the libraries
# the AI persona relies on most. Rerun when package versions change.
#
# Usage: ./tools/gen-api-reference.sh
#
# Requires: cabal, ghc. Writes to the repo's data/api-reference.txt.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/data/api-reference.txt"
WORK="$(mktemp -d /tmp/sabela-apicard.XXXXXX)"
# Temp dir retained for debugging; clean up manually.

echo "Generating API reference in $WORK"

# Modules to browse. Paired with a short caption that goes above each block.
MODULES=(
    "DataFrame:-- DataFrame: core dataframe ops"
    "DataFrame.Functions:-- DataFrame.Functions: column references, lifts, declareColumns"
    "DataFrame.Typed:-- DataFrame.Typed: compile-time-typed dataframe (PREFERRED — type-safe columns, better error messages)"
    "DataFrame.Display.Web.Plot:-- DataFrame.Display.Web.Plot: interactive HTML plots"
    "Granite.Svg:-- Granite.Svg: static SVG chart primitives"
)

cat > "$WORK/card.cabal" <<EOF
cabal-version: 3.0
name: card
version: 0.1
build-type: Simple

library
  default-language: Haskell2010
  build-depends: base, dataframe, granite, text
EOF

cat > "$WORK/cabal.project" <<EOF
packages: .
EOF

# Build a GHCi input script that browses each module.
SCRIPT="$WORK/browse.ghci"
{
    echo ":set prompt \"\""
    echo ":set prompt-cont \"\""
    for entry in "${MODULES[@]}"; do
        mod="${entry%%:*}"
        caption="${entry#*:}"
        echo "putStrLn \"\""
        echo "putStrLn \"$caption\""
        echo "putStrLn \"\""
        echo ":browse $mod"
    done
    echo ":quit"
} > "$SCRIPT"

echo "Resolving packages + launching GHCi (first run may take a few minutes)..."

RAW="$WORK/raw.txt"
(cd "$WORK" && cabal repl lib:card --repl-options=-v0 < "$SCRIPT") > "$RAW" 2>&1 || {
    echo "cabal repl failed; inspect $RAW" >&2
    tail -40 "$RAW" >&2
    exit 1
}

# Strip blank trailing lines, remove any control characters, drop GHCi prompt
# residue. Writes to OUT.
mkdir -p "$(dirname "$OUT")"
{
    echo "-- Generated by tools/gen-api-reference.sh. Do not edit by hand."
    echo
    # Keep everything from the first "-- DataFrame" caption onward.
    sed -n '/^-- DataFrame/,$p' "$RAW" \
        | tr -d '\r' \
        | sed -E 's/\x1B\[[0-9;]*[A-Za-z]//g' \
        | awk '
            # Collapse continuation lines (starting with whitespace) onto prior
            # line with a single space separator, producing one-line signatures.
            /^[[:space:]]/ {
                sub(/^[[:space:]]+/, " ")
                acc = acc $0
                next
            }
            {
                if (acc != "") print acc
                acc = $0
            }
            END { if (acc != "") print acc }
        ' \
        | sed -E 's/DataFrame\.Internal\.[[:alnum:]_.]+\.//g' \
        | sed -E 's/DataFrame\.Operations\.[[:alnum:]_]+\.//g' \
        | sed -E 's/DataFrame\.Display\.[[:alnum:]_]+\.//g' \
        | sed -E 's/DataFrame\.IO\.[[:alnum:]_]+\.//g' \
        | sed -E 's/DataFrame\.Errors\.//g' \
        | sed -E 's/Data\.Text\.Internal\.Text/Text/g' \
        | sed -E 's/[[:alnum:]_-]+-[0-9][0-9.]*:[[:alnum:]_.]+\.(Vector|Map|Set|IntMap|IntSet|ByteString|Text|HashMap|HashSet)/\1/g' \
        | sed -E 's/base-[0-9][0-9.]*:[[:alnum:]_.]+\.([[:alnum:]_]+)/\1/g' \
        | sed -E 's/\{-# UNPACK #-\}//g' \
        | sed -E 's/[[:space:]]+/ /g' \
        | grep -v '^-- Defined in' \
        | grep -v '^class \[safe\]' \
        | grep -v '^(DataFrame\.Operators' \
        | grep -v '^(DataFrame\.Typed\.Expr' \
        | sed -E 's/forall [^.]+\. //g' \
        | awk 'BEGIN { prev = "" } { if ($0 != prev || $0 == "") { print; prev = $0 } }'
} > "$OUT"

LINES=$(wc -l < "$OUT")
echo "Wrote $OUT ($LINES lines)"
echo "Rebuild sabela so the embedded reference card picks up the new content."
